dist: trusty
sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.12.9

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "FgmRP99D4vISj5b3uWJECd2WzeAwwI1lXZ6M15AuI8057X18RcqpRfiYQ4PLuXU5u3fFjpROK6AuuS5MBjC0bMgt0Y3kKdNHUwog1fOFklvcJ30MltuwTgwOFEWba1yuQ520+I0ZdPhDDu96MvS6jLchmpJCBpKt31zLsQOGLkm8VBK+784kR7HUwlDRkPG34vhS2/noJD7bdApAMiSym8n39QW0PAoNSGVOXZHWkQsiIXmJVz++4D3r5yqCUg91eU2kUtrpCLEi3RLWBoPRuPFcUonstYe1aT47dy3AfmLa+0QdCcAMg/dtuY3GGGhRkfkVgTl6O5U0F6TdGSaLmSLCWajq6uqEijsfMpVyFZC7RltBIA/55X6j1uMvwyOKYWWz+GKolzOESPuvHUdemmHT/aIYw2c4vsdWtgZ7oxRMD/z4byGXVgwIWS5obx1lMcauAdnbA/V2EScQfaoQ+IT3hpP7QXfofX7vc71G9CcZF1WHH6qHVwTjIgRj4DcVrloenqrqPPxUvtIpxayv/HKB7VoxuLoIoMKFGaEbAAF09JVKWMPM4Rbctr033rhcwVO7BrbGa7jAEC70byJA6oRSsLfEUYicHmfMYLWyXY+p4ZAuVs5/sIvNLAejZp8ZkGmuVzONiOF40l3yoxciyUOoCmc4+w1xzsMQRCLgJic="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete